service: severless-email

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: dev
  environment:
    MAIL_SERVICE: ${file(env.yml):${self:provider.stage}.MAIL_SERVICE}
    MAIL_USER: ${file(env.yml):${self:provider.stage}.MAIL_USER}
    MAIL_PASS: ${file(env.yml):${self:provider.stage}.MAIL_PASS}
    MAIL_PORT: ${file(env.yml):${self:provider.stage}.MAIL_PORT}
    MAIL_HOST: ${file(env.yml):${self:provider.stage}.MAIL_HOST}


functions:
  sendEmail:
    handler: emailHandler.sendEmail
    events:
      - http:
          path: send-email
          method: POST
